version: '3'
services:
  api_db:
    container_name: gearhunters-item-maria-db
    image: mariadb:latest
    volumes:
      - ./volumes/items:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306

  api:
    container_name: gearhunters-api
    build: ./api
    depends_on:
      - api_db
    environment:
      - DATABASE_URL=mysql+pymysql://root:${DB_PASSWORD}@api_db/${DB_NAME}
      - JWT_SECRET_KEY="secret"
      - DISPLAY=99
    command: ["python", "./app.py"]
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  
  backend:
    container_name: gearhunters-backend
    build: ./backend
    depends_on:
      - api
    command: ["python", "./app.py"]
    restart: always
    ports:
      - 8001:5000
    volumes:
      - ./backend:/app
    environment:
      - API_BASE_URL=http://api:8000
      - API_USER=${API_USER}
      - API_PASSWORD=${API_PASSWORD}